### ISSUE TITLE
Multiple Roblox Instance broken - mac

### ISSUE THREAD

**Issue by Thyssenkrupp234** [MainDabRblx/MultipleRobloxInstances#2]
It doesn't work, on mac. Creating a mutex should work just fine on Mac, but doesn't work. Any idea why it doesn't? And does it work on windows or no?

**Comment by MainDabRblx** [comment]
Sorry for answering very late, I did not notice the issues that popped up in this repository. 

The function Mutex does not exist on the MacOS platform. However, there is probably an equivalent of it in MacOS. Howeverm I am not familiar with MacOS development.
