### ISSUE TITLE
Multiple Roblox Instance working but apparently stop working

### ISSUE THREAD

**Issue by David-Maturana** [MainDabRblx/MultipleRobloxInstances#3]
**Describing the issue**

In fact bro the appworks, but some time later it stops working, example, i play jailbreak with y at account, i close all the roblox and thne i try to re open my alts and my accounts but only llows me open one instance (as normal)

i suggest you use an old version to fix it =D. This old version works perfetly and no bugs, i think is an error on the code.

So the solution is this bro, remake the program using this old program as template, put the text roblox instances... and put in the main github page the new that yo updated the roblox mutiple instances fixing some bugs. I will try it and i will tell you ;)

Good afternoon =D
[00 MultipleRobloxInstances.zip](https://github.com/MainDabRblx/MultipleRobloxInstances/files/9128248/00.MultipleRobloxInstances.zip)

**Comment by MainDabRblx** [comment]
I think you've been using the program incorrectly. When closing all the Roblox instances, did you also close the multiple roblox instance?

Also... there is **no** older version of this program at all.
